image: openjdk:8

options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew build
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t rmachnik/rebridge .
          - docker push rmachnik/rebridge:latest

#    - step:
#            name: Deploy to test
#            deployment: test
#            script:
#              - ssh $USER@$HOST_NAME
#              - docker pull rmachnik/rebridge:latest
#              - docker stop $(docker ps -a -q  --filter ancestor=rmachnik/rebridge)
#              - docker run -p 8080:8080 -d --rm rmachnik/rebridge

    - step:
        name: Deploy to test
        deployment: test
        script:
          - ssh $USER@$HOST_NAME
          - ./deploy.sh &