version: '3'
services:
  rebridge-backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      - "cassandra"
  cassandra:
    image: "cassandra:latest"
    ports:
    - "9042:9042"